<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vision_picking</name>
  <version>0.1.0</version>
  <description>Isaac Sim + ROS 2 + MoveIt 2によるビジョンピッキングの認識・制御ノード群</description>
  <maintainer email="noreply@example.com">vpicking</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>shape_msgs</depend>
  <depend>std_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>diagnostic_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>moveit_py</depend>
  <depend>moveit_configs_utils</depend>
  <depend>moveit_resources_panda_moveit_config</depend>
  <depend>cv_bridge</depend>
  <depend>tf_transformations</depend>
  <depend>py_trees</depend>
  <depend>py_trees_ros</depend>
  <depend>foxglove_msgs</depend>
  <depend>common</depend>
  <depend>control_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>topic_based_ros2_control</exec_depend>
  <exec_depend>trac_ik_kinematics_plugin</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
